functionsDirectory = "C:\\Users\\ruben\\Desktop\\IronHack\\projects\\module3-project\\project-glucoFit\\web\\gluco-fit\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\ruben\\Desktop\\IronHack\\projects\\module3-project\\project-glucoFit\\web\\gluco-fit\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\ruben\\Desktop\\IronHack\\projects\\module3-project\\project-glucoFit\\web\\gluco-fit"
command = "npm run build"
functions = "C:\\Users\\ruben\\Desktop\\IronHack\\projects\\module3-project\\project-glucoFit\\web\\gluco-fit\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]